10207_Megan Pretorius_SLD521_SA/Controllers/PaperController.cs
using _10207_Megan_Pretorius_SLD521_SA.Models.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _10207_Megan_Pretorius_SLD521_SA.Controllers
{
    [Authorize(Roles = "Author")]
    public class PaperController : Controller
    {
        PaperDbContext dbContext = new PaperDbContext();

        public ActionResult List()
        {
            var papers = dbContext.papers.Where(s => s.UserEmail == User.Identity.Name);
            return View(papers);
        }

        //GET: Paper
        [AllowAnonymous]
        public ActionResult PaperView()
        {
            return View(dbContext.papers.ToList());
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Paper papers, FormCollection formCollection)
        {
            if (ModelState.IsValid)
            {
                papers.UserEmail = User.Identity.Name;
                papers.TopicId = int.Parse(papers.TopicId.ToString());
                dbContext.papers.Add(papers);
                dbContext.SaveChanges();

                return RedirectToAction("List");
                //return View(paper);
            }
            else
                ModelState.AddModelError("", "Paper Not Added!");
            return View();
        }

        public ActionResult Edit()
        {
            return View();
        }

        [HttpGet]

        public ActionResult Edit(int? id)
        {
            var papers = dbContext.papers.Find(id);
            return View(papers);
        }

        [HttpPost]


        public ActionResult Edit(int? id, FormCollection formCollection)
        {
            var papers = dbContext.papers.Find(id);
            if (ModelState.IsValid)
            {
                if (TryUpdateModel(papers))
                {
                    dbContext.SaveChanges();
                    return RedirectToAction("List");
                }
            }
            else
            {
                ModelState.AddModelError("", "Paper Not updated!");
            }
            return View(papers);
        }

        public ActionResult Delete()
        {
            return View();
        }

        [HttpPost]

        public ActionResult Delete(int? id, FormCollection formcollection)
        {
            try
            {
                var papers = dbContext.papers.Find(id);
                dbContext.papers.Remove(papers);
                dbContext.SaveChanges();
                return RedirectToAction("List");
            }
            catch
            {
                ModelState.AddModelError("", "Paper Not deleted!");
            }
            return View();
            
        }
    }
}

10207_Megan Pretorius_SLD521_SA/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - SLD SA Megan Pretorius</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <style>
        #foot {
            /*position: fixed;*/
            bottom: 10%;
            text-align: center
        }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("SACLA", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Papers", "PaperView", "Paper")</li>
                    <li>@Html.ActionLink("News", "News", "Home")</li>
                    <li>@Html.ActionLink("About Us", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <div id="foot">
            <footer>
                <p>&copy; @DateTime.Now.Year - 10207 Megan Pretorius</p>
            </footer>
        </div>
        
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>